### ISSUE TITLE
ModuleNotFoundError: No module named 'django_bootstrap5'

### ISSUE THREAD

**Issue by Jason-Omondi** [darryl22/billing-app-prototype#1]
I'm running into an issue with our Django project that I could use your help with. I recently installed the django_bootstrap5 package using pip, but when I run the python3 manage.py runserver command, I get a ModuleNotFoundError for the django_bootstrap5 module. I have tried re-installing the package and even running pip freeze to ensure that the package is installed, but the error persists.

I am working with Python 3.11 and Django 4.1.7. I suspect that there might be an issue with the package installation or the way the module is being imported by Django.
Here is the error message: **ModuleNotFoundError: No module named 'django_bootstrap5'**

**Comment by darryl22** [comment]
Hi,

Let me look into it to see if there's anything I can do. Maybe I pushed it
badly. In the meantime try using a virtual environment with pipenv instead
of the other one, you just need to type pipenv install in the command line
and it should install all the other packages.
